### PR TITLE
New Julia v0.7/v1.0 approach

### PR DESCRIPTION
**Pull request by andyferris**
* One basic `Table` type which is an `AbstractArray{<:NamedTuple}`
 * Rows are `NamedTuples`
 * That's about it!

### CODE REVIEW

**Comment by cstjean** [comment]
Cool!

I haven't thought it through, but why not allow arbitrary objects in addition to tuples? Eg. `Table(Vector{Student})`

**Comment by andyferris** [comment]
Thanks. Are you referring to the row (element) type here being forced to be `NamedTuple`?

So my grand plan goes like:

 * Tables are basically nested containers (e.g a table is a collection of rows, which are themselves collections of fields). In particular, a *relation* (as in relational algebra) is typically defined to be a collection of (named) tuples, which is what we're rolling with here.
 * Base and SplitApplyCombine provides tools for nested containers that are also useful for relational algebra (e.g there's an `innerjoin` that doesn't know anything particular about `Table` or `NamedTuple`)
 * The `Table` type here just provides column-base storage rather than using row-based `Vector{NamedTuple}`. I hope this package *won't* contain much more of an interface beyond that.
 * `AcceleratedArrays` will be available to help speed up operations, e.g joins via sort-merge algorithm or whatever.

We can look at other container types in the future... higher on the list for me is that there can be `Set`s of rows, `Dict`s of rows, etc, and these should also behave as relations. Having other row types could also be considered but I'm hoping this package remains focussed and minimal.

**Comment by andyferris** [comment]
Oh and I'd love to have something like `DataFrame{N} <: AbstractArray{NamedTuple, N}` type where you can add and delete columns, etc.

**Comment by andyferris** [comment]
CI will rely on https://github.com/JuliaLang/METADATA.jl/pull/16017 so I'm waiting for that to hit the General registry before merging this.

**Comment by cstjean** [comment]
My mistake - I interpreted `Rows are NamedTuples` to mean that you were switching to row-based storage, but I see that it's just an interface.

**Pull request closed without merging**
