### PR TITLE
`AbstractTable` interface

### PR DESCRIPTION
**Pull request by andyferris**
We can now create new subtypes of `AbstractTable` that e.g. store data in a different format or include an index or are sorted or whatever. `Table` itself is rather small now. 
- Similarly for `AbstractRow`, etc
- These should define `names()` (or `name()`) as a pure function of the type.
- These should define `get` which returns a tuple of columns for a table (previously was assumed to be `data` field
- Now only support Julia 0.5

### CODE REVIEW

**Comment by c42f** [comment]
This is a pretty epic amount of refactoring!  I'm not going to pretend to look through it all, but the general idea sounds great :-)  If you want me to have a closer look at anything specific here let me know.

**Comment by andyferris** [comment]
> If you want me to have a closer look at anything specific here let me know.

Only a general question. The original code was hand-optimized to be efficient (e.g. I looked at `getindex` and fiddled with it to minimize the llvm/native code). Now I've changed everything... I'm wondering what a good tool is for comparing speeds between revisions (something like nanosoldier is for Julia)?

**Comment by c42f** [comment]
BenchmarkTools.jl seems to be the main package to look at, you just need a set of meaningful benchmark cases and it will take care of running them locally.

As for hosted benchmarking services, I don't know about anything that exists there.  I believe nanosolider is hosted on dedicated machines at MIT.  You might possibly try doing benchmarking on a CI service, but the noise introduced by the VM environment might be too large to get anything useful out of it.

**Comment by nalimilan** [comment]
There's also PkgBenchmark.jl.

**Comment by c42f** [comment]
Thanks, PkgBenchmarks looks really useful.

**Pull request closed without merging**
