### PR TITLE
Julia 0.5 compatability updates

### PR DESCRIPTION
**Pull request by davidanthoff**
I haven't tested this on julia 0.4, so we should be certain that the travis build on julia 0.4 works before this gets merged.

### CODE REVIEW

**Comment by andyferris** [comment]
Oh - thanks for this!

**Comment by davidanthoff** [comment]
@andyferris Alright, I think this is ready to merge, and maybe you could also tag a release so that this is smooth sailing for julia 0.5 users?

**Comment by davidanthoff** [comment]
@andyferris Bump, any chance you could merge this soon and tag a release? It would clear up julia 0.5 compat problems. Thanks!

**Comment by andyferris** [comment]
Sorry David! I've been distracted. Merged now.

**Pull request merged**
