### PR TITLE
Support Tables.materializer

### LINKED ISSUE #40: Support for Tables.materializer
Currently `materializer(::TypedTable)` returns the default `Tables.columntable`, so

    materializer(table)(columns(table)) 

currently returns a `NamedTuple` instead of a `TypedTables.Table`. A specialized method of `materializer` for `TypedTable` could be quite useful.

### PR DESCRIPTION
**Pull request by oschulz**
Closes #40

### CODE REVIEW

**Comment by oschulz** [comment]
@andyferris , if there are no objections, I'd be glad for a speedy merge. I'm giving a talk on Julia this week and would like to use this feature, if possible (TypedTables is *so* useful). A tag would be even better (I'll be handing out stuff for people to try), but I don't know the release policy for TypedTables.

**Comment by andyferris** [comment]
Done!

Would you like a tag with or without the changes in #39?

**Comment by andyferris** [comment]
See https://github.com/JuliaLang/METADATA.jl/pull/19792

I'll merge #39 to master to let it percolate, but let me know if a release of that is useful.

**Comment by oschulz** [comment]
Sorry for the late reply, was travelling. A tag including #39 would be great!

I use TypedTables mainly as an on-the-fly column-stored array-of-structs. I am working on an ArrayOfStructs.jl (as a replacement for the outdated StructsOfArrays.jl) with deep nesting based on ArraysOfArrays, but there's still a way to go there.

**Comment by oschulz** [comment]
Thanks again for the release, @andyferris !

**Comment by andyferris** [comment]
No worries - how did the talk go?

**Comment by oschulz** [comment]
It went well, thanks - I think I managed to generate quite some interest for Julia. :-)

**Pull request merged**
